package com.scale.workercapture;

import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.hardware.camera2.*;import android.media.*;import android.view.*;import android.widget.*;import java.io.*;import java.nio.*;import java.util.*;

public class CameraActivity extends Activity implements TextureView.SurfaceTextureListener{
 TextureView preview; CameraDevice camera; CameraCaptureSession session; ImageReader reader; String name,id; int step=0; String workerPath,handPath; Handler handler=new Handler(Looper.getMainLooper());
 int bg=Color.rgb(11,11,12),text=Color.rgb(242,240,234),muted=Color.rgb(139,139,144),accent=Color.rgb(232,228,218);
 @Override public void onCreate(Bundle b){super.onCreate(b);name=getIntent().getStringExtra("name");id=getIntent().getStringExtra("deviceId");build();if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.CAMERA},7);}
 TextView t(String s,float z,int c){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(c);return x;}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);LinearLayout top=new LinearLayout(this);top.setPadding(20,18,20,10);top.setGravity(Gravity.CENTER_VERTICAL);TextView cancel=t("‹ Cancel",13,muted);top.addView(cancel,new LinearLayout.LayoutParams(0,50,1));TextView st=t("Step "+(step+1)+" of 2",11,muted);top.addView(st);root.addView(top);TextView title=t(step==0?"Worker photo":"Hand photo",38,text);title.setPadding(22,8,22,6);root.addView(title);TextView sub=t(name+" · "+id,13,muted);sub.setPadding(22,0,22,12);root.addView(sub);FrameLayout frame=new FrameLayout(this);frame.setBackgroundColor(Color.BLACK);preview=new TextureView(this);preview.setSurfaceTextureListener(this);frame.addView(preview,new FrameLayout.LayoutParams(-1,-1));root.addView(frame,new LinearLayout.LayoutParams(-1,0,1));TextView hint=t("Tap the preview to focus",13,muted);hint.setGravity(Gravity.CENTER);root.addView(hint,new LinearLayout.LayoutParams(-1,48));Button shutter=new Button(this);shutter.setText("●  CAPTURE");shutter.setTextColor(Color.BLACK);shutter.setBackgroundColor(accent);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,58);p.setMargins(22,8,22,22);root.addView(shutter,p);cancel.setOnClickListener(v->finish());shutter.setOnClickListener(v->capture());preview.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_UP)focus(e.getX(),e.getY());return true;});setContentView(root);}
 @Override public void onSurfaceTextureAvailable(SurfaceTexture s,int w,int h){openCamera();} public boolean onSurfaceTextureDestroyed(SurfaceTexture s){return true;}public void onSurfaceTextureSizeChanged(SurfaceTexture s,int w,int h){}public void onSurfaceTextureUpdated(SurfaceTexture s){}
 void openCamera(){try{CameraManager cm=(CameraManager)getSystemService(CAMERA_SERVICE);String cid=cm.getCameraIdList()[0];CameraCharacteristics cc=cm.getCameraCharacteristics(cid);android.util.Size[] sizes=cc.get(CameraCharacteristics.SCALER_STREAM_CONFIGURATION_MAP).getOutputSizes(ImageFormat.JPEG);android.util.Size sz=sizes[0];for(android.util.Size q:sizes)if(q.getWidth()*q.getHeight()>sz.getWidth()*sz.getHeight())sz=q;reader=ImageReader.newInstance(sz.getWidth(),sz.getHeight(),ImageFormat.JPEG,2);reader.setOnImageAvailableListener(r->{Image im=r.acquireLatestImage();if(im==null)return;ByteBuffer b=im.getPlanes()[0].getBuffer();byte[] data=new byte[b.remaining()];b.get(data);im.close();handler.post(()->savePhoto(data));},handler);if(checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)cm.openCamera(cid,new CameraDevice.StateCallback(){public void onOpened(CameraDevice c){camera=c;startPreview();}public void onDisconnected(CameraDevice c){c.close();}public void onError(CameraDevice c,int e){c.close();}},handler);}catch(Exception e){Toast.makeText(this,"Camera error: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 void startPreview(){try{SurfaceTexture st=preview.getSurfaceTexture();st.setDefaultBufferSize(preview.getWidth(),preview.getHeight());Surface s=new Surface(st);CaptureRequest.Builder b=camera.createCaptureRequest(CameraDevice.TEMPLATE_PREVIEW);b.addTarget(s);camera.createCaptureSession(Arrays.asList(s,reader.getSurface()),new CameraCaptureSession.StateCallback(){public void onConfigured(CameraCaptureSession x){session=x;try{session.setRepeatingRequest(b.build(),null,handler);}catch(Exception ignored){}}public void onConfigureFailed(CameraCaptureSession x){}},handler);}catch(Exception ignored){}}
 void focus(float x,float y){if(session==null||camera==null)return;try{CaptureRequest.Builder b=camera.createCaptureRequest(CameraDevice.TEMPLATE_PREVIEW);b.addTarget(new Surface(preview.getSurfaceTexture()));b.set(CaptureRequest.CONTROL_AF_MODE,CaptureRequest.CONTROL_AF_MODE_AUTO);b.set(CaptureRequest.CONTROL_AF_TRIGGER,CaptureRequest.CONTROL_AF_TRIGGER_START);session.capture(b.build(),null,handler);}catch(Exception ignored){}}
 void capture(){if(session==null)return;try{CaptureRequest.Builder b=camera.createCaptureRequest(CameraDevice.TEMPLATE_STILL_CAPTURE);b.addTarget(reader.getSurface());b.set(CaptureRequest.CONTROL_AF_MODE,CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_PICTURE);session.capture(b.build(),null,handler);}catch(Exception e){Toast.makeText(this,"Capture failed",Toast.LENGTH_SHORT).show();}}
 void savePhoto(byte[] data){try{File dir=new File(getFilesDir(),"workers");dir.mkdirs();String fn=System.currentTimeMillis()+"_"+(step==0?"worker":"hand")+".jpg";File f=new File(dir,fn);FileOutputStream o=new FileOutputStream(f);o.write(data);o.close();if(step==0){workerPath=f.getAbsolutePath();step=1;if(camera!=null){camera.close();camera=null;}build();if(preview.isAvailable())openCamera();}else{handPath=f.getAbsolutePath();Intent out=new Intent();out.putExtra("workerPath",workerPath);out.putExtra("handPath",handPath);out.putExtra("name",name);out.putExtra("deviceId",id);setResult(RESULT_OK,out);finish();}}catch(Exception e){Toast.makeText(this,"Save failed: "+e.getMessage(),Toast.LENGTH_SHORT).show();}}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==7&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED&&preview.isAvailable())openCamera();else if(r==7)Toast.makeText(this,"Camera permission is required",Toast.LENGTH_LONG).show();}
}
