package com.scale.workercapture;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity {
    LinearLayout root,list; TextView count; ArrayList<Worker> workers=new ArrayList<>();
    int bg=Color.rgb(11,11,12), text=Color.rgb(242,240,234), muted=Color.rgb(139,139,144), accent=Color.rgb(232,228,218), surface=Color.rgb(19,19,21);
    int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
    TextView tv(String s,float size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setGravity(Gravity.CENTER_VERTICAL);return t;}
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(bg);load();showList();}
    void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);setContentView(root);LinearLayout h=new LinearLayout(this);h.setPadding(dp(22),dp(18),dp(22),dp(14));h.setGravity(Gravity.CENTER_VERTICAL);TextView brand=tv("Scale",30,text);h.addView(brand,new LinearLayout.LayoutParams(0,dp(50),1));count=tv(workers.size()+" captured",12,muted);h.addView(count,new LinearLayout.LayoutParams(-2,dp(42)));Button menu=button("⋮");menu.setTextColor(muted);menu.setBackgroundColor(bg);h.addView(menu,new LinearLayout.LayoutParams(dp(48),dp(48)));menu.setOnClickListener(v->showMenu(menu));root.addView(h);}
    Button button(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.rgb(17,17,17));b.setTextSize(14);b.setAllCaps(false);b.setBackgroundColor(accent);return b;}
    void showMenu(View anchor){PopupMenu p=new PopupMenu(this,anchor);p.getMenu().add("Export ZIP");p.getMenu().add("Delete All");p.setOnMenuItemClickListener(i->{if(i.getTitle().toString().equals("Export ZIP")){new Thread(()->{try{File f=ZipExporter.make(this,workers);runOnUiThread(()->Toast.makeText(this,f==null?"No complete workers to export":"ZIP saved in app storage",Toast.LENGTH_LONG).show());}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Export failed: "+e.getMessage(),Toast.LENGTH_LONG).show());}}).start();}else{new AlertDialog.Builder(this).setTitle("Delete all workers?").setMessage("This permanently removes all workers, photos and metadata.").setNegativeButton("Cancel",null).setPositiveButton("Delete Everything",(d,w)->{for(Worker x:new ArrayList<>(workers))deleteWorker(x);showList();}).show();}return true;});p.show();}
    void showList(){base();TextView title=tv("Captured workers",38,text);title.setPadding(dp(22),dp(24),dp(22),dp(4));root.addView(title);TextView sub=tv(workers.size()+" total · "+complete()+" complete",13,muted);sub.setPadding(dp(22),0,dp(22),dp(18));root.addView(sub);ScrollView sv=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(dp(22),0,dp(22),dp(100));sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));for(int i=0;i<workers.size();i++)addRow(workers.get(i),i);Button nb=button("+ New Worker");LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(58));bp.setMargins(dp(22),dp(10),dp(22),dp(20));root.addView(nb,bp);nb.setOnClickListener(v->showForm());}
    int complete(){int n=0;for(Worker w:workers)if(w.workerPath!=null&&!w.workerPath.isEmpty()&&w.handPath!=null&&!w.handPath.isEmpty())n++;return n;}
    void addRow(Worker w,int idx){LinearLayout row=new LinearLayout(this);row.setPadding(0,dp(10),0,dp(10));row.setGravity(Gravity.CENTER_VERTICAL);TextView no=tv(String.format("%02d",idx+1),12,muted);row.addView(no,new LinearLayout.LayoutParams(dp(30),dp(80)));LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);TextView n=tv(w.name,18,text);TextView id=tv("ID "+w.deviceId,12,muted);info.addView(n);info.addView(id);row.addView(info,new LinearLayout.LayoutParams(0,dp(80),1));Button del=button("Delete");del.setTextColor(Color.rgb(220,80,80));del.setBackgroundColor(surface);row.addView(del,new LinearLayout.LayoutParams(dp(86),dp(48)));del.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Delete "+w.name+"?").setMessage("This permanently removes both photos and the record from this device.").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,x)->{deleteWorker(w);showList();}).show());list.addView(row);}
    void showForm(){base();TextView title=tv("New worker",40,text);title.setPadding(dp(22),dp(30),dp(22),dp(12));root.addView(title);LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(dp(22),0,dp(22),0);EditText name=new EditText(this);name.setHint("Worker name");name.setTextColor(text);name.setHintTextColor(muted);f.addView(name,new LinearLayout.LayoutParams(-1,dp(64)));EditText id=new EditText(this);id.setHint("5-digit Device ID");id.setInputType(2);id.setTextColor(text);id.setHintTextColor(muted);f.addView(id,new LinearLayout.LayoutParams(-1,dp(64)));root.addView(f);Space sp=new Space(this);root.addView(sp,new LinearLayout.LayoutParams(1,0,1));Button go=button("Capture photos");LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(60));p.setMargins(dp(22),dp(10),dp(22),dp(30));root.addView(go,p);go.setOnClickListener(v->{String n=name.getText().toString().trim(),d=id.getText().toString().trim();if(n.isEmpty()||!d.matches("\\d{5}")){Toast.makeText(this,"Enter a name and exactly 5 digits",Toast.LENGTH_SHORT).show();return;}Intent i=new Intent(this,CameraActivity.class);i.putExtra("name",n);i.putExtra("deviceId",d);startActivityForResult(i,42);});}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==42){if(c==RESULT_OK&&d!=null){workers.add(new Worker(System.currentTimeMillis(),d.getStringExtra("name"),d.getStringExtra("deviceId"),d.getStringExtra("workerPath"),d.getStringExtra("handPath")));save();}load();showList();}}
    void load(){workers.clear();File dir=new File(getFilesDir(),"workers");dir.mkdirs();File meta=new File(dir,"workers.tsv");if(!meta.exists())return;try{BufferedReader br=new BufferedReader(new FileReader(meta));String s;while((s=br.readLine())!=null){String[] a=s.split("\\t",-1);if(a.length>=5)workers.add(new Worker(Long.parseLong(a[0]),a[1],a[2],a[3],a[4]));}br.close();}catch(Exception ignored){}}
    void save(){try{File meta=new File(getFilesDir(),"workers/workers.tsv");BufferedWriter bw=new BufferedWriter(new FileWriter(meta,false));for(Worker w:workers)bw.write(w.id+"\t"+w.name.replace("\t"," ")+"\t"+w.deviceId+"\t"+(w.workerPath==null?"":w.workerPath)+"\t"+(w.handPath==null?"":w.handPath)+"\n");bw.close();}catch(Exception ignored){}}
    void deleteWorker(Worker w){if(w.workerPath!=null)new File(w.workerPath).delete();if(w.handPath!=null)new File(w.handPath).delete();workers.remove(w);save();}
    static class Worker{long id;String name,deviceId,workerPath,handPath;Worker(long i,String n,String d,String w,String h){id=i;name=n;deviceId=d;workerPath=w;handPath=h;}}
}
